plugins {
    id 'java'
    id 'com.moowork.node' version '1.3.1'
}

repositories {
    jcenter()
}

dependencies {
    // Define your Java dependencies here
}

task installNodeTool(type: NodeTask) {
    version = '14.x'
    // Additional configuration options for NodeTool task can be set here
}

task installDependencies(type: NpmTask) {
    dependsOn installNodeTool
    command = 'install'
    workingDir = projectDir
    // Additional configuration options for Npm task can be set here
}

task buildApplication(type: NpmTask) {
    dependsOn installDependencies
    command = 'run build'
    workingDir = projectDir
    // Additional configuration options for Npm task can be set here
}
